###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing import Dict, Generic, List, Optional, TypeVar, Union, Literal

from . import types
from .types import Checked, Check

###############################################################################
#
#  These types are used for streaming, for when an instance of a type
#  is still being built up and any of its fields is not yet fully available.
#
###############################################################################

T = TypeVar('T')
class StreamState(BaseModel, Generic[T]):
    value: T
    state: Literal["Pending", "Incomplete", "Complete"]


class APIRequest(BaseModel):
    path: Optional[str] = None
    method: Optional[types.HTTPMethod] = None
    params: Dict[str, Optional[str]]
    request_body: Optional[str] = None

class APIRequestFormer(BaseModel):
    params: Dict[str, Optional[str]]

class DynamicAPIRequest(BaseModel):
    path: Optional[str] = None
    method: Optional[types.HTTPMethod] = None
    params: Optional[Dict[str, Optional[str]]] = None
    request_body: Optional["DynamicObject"] = None

class DynamicJsonObject(BaseModel):
    model_config = ConfigDict(extra='allow')

class DynamicObject(BaseModel):
    model_config = ConfigDict(extra='allow')

class RequestBody(BaseModel):
    """"""
    required: List[str]
    required_types: List[str]
    all_params: List[str]
    all_types: List[str]

class RequestDataStorage(BaseModel):
    required: List[str]
    required_types: List[str]
    all_params: List[str]
    all_types: List[str]

class Resume(BaseModel):
    name: Optional[str] = None
    email: Optional[str] = None
    experience: List[str]
    skills: List[str]
