###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing_extensions import TypeAlias
from typing import Dict, Generic, List, Literal, Optional, TypeVar, Union


T = TypeVar('T')
CheckName = TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str

class Checked(BaseModel, Generic[T,CheckName]):
    value: T
    checks: Dict[CheckName, Check]

def get_checks(checks: Dict[CheckName, Check]) -> List[Check]:
    return list(checks.values())

def all_succeeded(checks: Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))



class DynamicEnum(str, Enum):
    pass

class DynamicJsonEnum(str, Enum):
    pass

class HTTPMethod(str, Enum):
    
    GET = "GET"
    DELETE = "DELETE"
    POST = "POST"
    PATCH = "PATCH"
    PUT = "PUT"

class APIRequest(BaseModel):
    path: str
    method: "HTTPMethod"
    params: Dict[str, str]
    request_body: Optional[str] = None

class APIRequestFormer(BaseModel):
    params: Dict[str, str]

class DynamicAPIRequest(BaseModel):
    path: str
    method: "HTTPMethod"
    query_params: Optional[Dict[str, str]] = None
    request_body: Optional["DynamicObject"] = None

class DynamicJsonObject(BaseModel):
    model_config = ConfigDict(extra='allow')

class DynamicObject(BaseModel):
    model_config = ConfigDict(extra='allow')

class RequestBody(BaseModel):
    """"""
    required: List[str]
    required_types: List[str]
    all_params: List[str]
    all_types: List[str]

class RequestDataStorage(BaseModel):
    required: List[str]
    required_types: List[str]
    all_params: List[str]
    all_types: List[str]

class Resume(BaseModel):
    name: str
    email: str
    experience: List[str]
    skills: List[str]
